name: Build Docker images

on:
  push:
    branches: mautic4

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [apache, fpm]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}        
      - name: Build ${{ matrix.image }} image
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.image }}/Dockerfile
          push: true
          tags: zubairov/mautic:v4-${{ matrix.image }}
