name: Build Docker images

on:
  push:
    branches: mautic4

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [apache, fpm]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build ${{ matrix.image }} image
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.image }}/Dockerfile
          push: false
          tags: mautic/mautic:v4-${{ matrix.image }}
